### ISSUE TITLE
Cant connect to Hass

### ISSUE THREAD

**Issue by WaaromZoMoeilijk** [hassio-addons/addon-control-panel#3]
# Problem/Motivation

> Can't connect to HASS

## Expected behavior

> Auto detect server would fill in the proper server details.

## Actual behavior

> When i connect to https://192.168.33.55:7080, I get the popup: `Unable to connect to Home Assistant. Please check the Server URL is accessible from this device or change the URL below:`

> Setting it manually also makes no difference, also entered the password manually. Tried: http and https, LAN ip and localhost, port 8123 (which i think it should connect to)

Hardware: RPI2
HASS server is not accesable via WAN, I only use it on LAN.
IP: https://192.168.33.55:8123

Control panel addon is installed, config:
```
{
  "log_level": "info",
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "ipv6": false
}

```
Addon log file: 
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-hacp: applying... 
[fix-attrs.d] 01-hacp: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Home Assistant Control Panel v1.0.0
 Simple to use control panel for the ultimate home automation setup
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 03-version-requirements.sh: executing... 
[cont-init.d] 03-version-requirements.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 11-nginx.sh: executing... 
[cont-init.d] 11-nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
starting version 3.2.4
```

System log
```
starting version 3.2.4
18-04-30 19:11:00 INFO (MainThread) [__main__] Initialize Hassio setup
18-04-30 19:11:01 INFO (MainThread) [__main__] Setup HassIO
18-04-30 19:11:01 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to supervisor homeassistant/armhf-hassio-supervisor with version 0.102
18-04-30 19:11:01 INFO (MainThread) [hassio.misc.host_control] Send 'info' to HostControl.
18-04-30 19:11:02 INFO (MainThread) [hassio.misc.host_control] Receive from HostControl: { "type": "resinos", "version": "1.3", "last_version": "1.3", "hostname": "hassio", "features": ["shutdown", "reboot", "update", "hostname"], "os": "GNU/Linux" }.
18-04-30 19:11:02 INFO (SyncWorker_2) [hassio.docker.interface] Attach to image homeassistant/raspberrypi2-homeassistant with version 0.68.0
18-04-30 19:11:16 INFO (MainThread) [hassio.addons.git] Load addon /data/addons/git/a0d7b954 repository
18-04-30 19:11:16 INFO (MainThread) [hassio.addons.git] Load addon /data/addons/core repository
18-04-30 19:11:17 INFO (MainThread) [hassio.addons] Load addons: 34 all - 34 new - 0 remove
18-04-30 19:11:17 INFO (SyncWorker_2) [hassio.docker.interface] Attach to image hassioaddons/control-panel-armhf with version 1.0.0
18-04-30 19:11:17 INFO (SyncWorker_3) [hassio.docker.interface] Attach to image hassioaddons/ftp-armhf with version 1.0.0
18-04-30 19:11:17 INFO (SyncWorker_2) [hassio.docker.interface] Attach to image homeassistant/armhf-addon-nginx_proxy with version 1.2
18-04-30 19:11:17 INFO (SyncWorker_4) [hassio.docker.interface] Attach to image homeassistant/armhf-addon-samba with version 3.0
18-04-30 19:11:17 INFO (SyncWorker_1) [hassio.docker.interface] Attach to image homeassistant/armhf-addon-ssh with version 3.4
18-04-30 19:11:17 INFO (SyncWorker_6) [hassio.docker.interface] Attach to image homeassistant/armhf-addon-configurator with version 0.2.7
18-04-30 19:11:17 INFO (SyncWorker_3) [hassio.docker.interface] Attach to image homeassistant/armhf-addon-letsencrypt with version 2.2
18-04-30 19:11:17 INFO (MainThread) [hassio.updater] Fetch update data from https://raw.githubusercontent.com/home-assistant/hassio/master/version.json
18-04-30 19:11:18 INFO (MainThread) [hassio.snapshots] Found 1 snapshot files
18-04-30 19:11:18 INFO (MainThread) [hassio.addons] Startup initialize run 0 addons
18-04-30 19:11:18 INFO (MainThread) [__main__] Run HassIO
18-04-30 19:11:18 INFO (MainThread) [hassio.misc.dns] Start DNS port forwarding for host add-ons
18-04-30 19:11:18 INFO (MainThread) [hassio.core] Ignore Hass.io auto updates on dev channel
18-04-30 19:11:18 INFO (MainThread) [hassio.core] Start API on 172.30.32.2
18-04-30 19:11:18 INFO (MainThread) [hassio.addons] Startup system run 1 addons
18-04-30 19:11:18 INFO (SyncWorker_0) [hassio.docker.interface] Clean hassioaddons/control-panel-armhf docker application
18-04-30 19:11:21 INFO (SyncWorker_0) [hassio.docker.addon] Start docker addon hassioaddons/control-panel-armhf with version 1.0.0
18-04-30 19:11:23 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_control-panel/info access from a0d7b954_control-panel
18-04-30 19:11:23 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_control-panel/info access from a0d7b954_control-panel
18-04-30 19:11:23 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_control-panel/info access from a0d7b954_control-panel
18-04-30 19:11:24 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_control-panel/info access from a0d7b954_control-panel
18-04-30 19:11:24 INFO (MainThread) [hassio.api.security] /addons access from a0d7b954_control-panel
18-04-30 19:11:24 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_control-panel/info access from a0d7b954_control-panel
18-04-30 19:11:25 INFO (MainThread) [hassio.api.security] /addons access from a0d7b954_control-panel
18-04-30 19:11:26 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_control-panel/info access from a0d7b954_control-panel
18-04-30 19:11:26 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_control-panel/info access from a0d7b954_control-panel
18-04-30 19:11:26 INFO (MainThread) [hassio.addons] Startup services run 1 addons
18-04-30 19:11:27 INFO (SyncWorker_1) [hassio.docker.interface] Clean homeassistant/armhf-addon-ssh docker application
18-04-30 19:11:30 INFO (SyncWorker_1) [hassio.docker.addon] Start docker addon homeassistant/armhf-addon-ssh with version 3.4
18-04-30 19:11:35 INFO (SyncWorker_6) [hassio.docker.interface] Clean homeassistant/raspberrypi2-homeassistant docker application
18-04-30 19:11:40 INFO (SyncWorker_6) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi2-homeassistant with version 0.68.0
18-04-30 19:12:50 INFO (MainThread) [hassio.homeassistant] Detect a running Home-Assistant instance
18-04-30 19:12:50 INFO (MainThread) [hassio.addons] Startup application run 1 addons
18-04-30 19:12:50 INFO (SyncWorker_9) [hassio.docker.interface] Clean homeassistant/armhf-addon-configurator docker application
18-04-30 19:12:54 INFO (SyncWorker_9) [hassio.docker.addon] Start docker addon homeassistant/armhf-addon-configurator with version 0.2.7
18-04-30 19:12:59 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
18-04-30 19:12:59 INFO (MainThread) [hassio.core] Hass.io is up and running
```

# configuration.yaml:
```
http:
  base_url: https://192.168.33.55:8123
  api_password: !secret password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  cors_allowed_origins:
    - https://192.168.3.55:7080
    - https://127.0.0.1:7080
```

Please advise.
Kind regards,

Ezra

**Comment by dovydasgulbinas** [comment]
I can only add to this issue. It looks like the request Headers are missing (Access-Control-Allow-Origin) for connecting from the same domain
<img width="585" alt="screen shot 2018-05-01 at 22 30 45" src="https://user-images.githubusercontent.com/13219260/39489952-d9dcc788-4d8f-11e8-8ae6-d7eb7df38a8b.png">

**Comment by nunoronconcouto** [comment]
hi..
I have some error... please help

**Comment by catcam** [comment]
same here ... rpi3 hass.io
![image](https://user-images.githubusercontent.com/12870243/39947378-f59011c6-5571-11e8-9980-98a7145856f7.png)

**Comment by oreinis** [comment]
hi,
i had the same problem but it fixed.
when it asks for the url enter it like this:
https://IP_ADDRESS:8123?api_password=API_PASSWORD.

now go to settings and delete the api password from the url and enter it where it asks for api password.

**Comment by frenck** [comment]
I see IP addresses with HTTPS...
That will never work, you cannot have a valid certificate for the IP address...
(unless you have created a self signed one and added it to your client operating system).

These listings above are not bugs, they are mainly caused by configuration.
Please see the community forums for more information and/or questions.

**Comment by karlg** [comment]
I also have this problem.
I do not believe it is a support request issue, but a bug with the software. If the former, you would see an isolated problem brought up by a single person. Here, you have many people with the same issue. It's more because you can be sure there will be lots of people who gave it a go and gave up.

I would think that if software relies on a particular setup of the network environment (i.e. a setup beyond its control) to work, then it cannot expect to work for all, or even many people. It's like saying that you've built a new car, but, oh, I didn't tell you that it can only run on blue roads.

Don't get me wrong: this is not an attack, I am merely trying to point out what seems to me to be a misapprehension by the developers.

Home-assistant is a great app. Control panel looks good too, but I can't run it. But, if, in order to make it work, people have to change their router settings, or install or muck around with their DNS or SSL settings, then, to me, it seems like you are limiting the audience of your app - as well as Home-assistant's.

There's also a security issue here: what if, in changing the settings to support the control panel, people  turned it off and opened their environment to the internet/hackers? Nobody wants that, but forcing people to fiddle with settings they might not properly understand could easily cause them to compromise their security.

Please: Control Panel needs to work autonomously.

All the best!!

**Comment by frenck** [comment]
@karlg Thank you for your feedback.
An add-on is essential a Docker container running software provided externally. 
Please refer to the author of the actual software: 

http://reformedreality.com/home-assistant-control-panel

I would only able to fix add-on issues, which this is absolutely not (impossible since the add-on serves only 1 static file, which works...)

<blockquote><img src="https://reformedreality.com/logo.svg" width="48" align="right"><div><strong><a href="http://reformedreality.com/home-assistant-control-panel">Home Assistant Control Panel</a></strong></div><div>An Angular Control Panel for Home Assistant. Automate your home with this simple to use, fully configurable, Hassio control panel UI.</div></blockquote>

**Comment by karlg** [comment]
Thanks frenck!
Understood. There are issues.

**Comment by asimmetrico** [comment]
Hello, I experience exactly the same problem. It's a pity since the control panel is really nice.
Please help 

Thanks

Al

**Comment by Frits1980** [comment]
I don't get it. This issue is closed because there is a sollution? Because if there is a sollution I'm missing it.
