### ISSUE TITLE
Doesn't scale on mobile

### ISSUE THREAD

**Issue by ghost** [hassio-addons/addon-control-panel#5]
# Problem/Motivation

The application doesn't scale to fit my screen better on mobile. Although the buttons seem to be smaller, the text in them is not so it overflows and overlaps.

## Expected behavior

Scaling of text and icons to better fit the screen size.

## Actual behavior

Poor scaling so there is overlapping and overflowing text

## Steps to reproduce

Open the control panel on mobile. I viewed it on a Pixel Phone.

## Screenshot
![alt text](https://lh3.googleusercontent.com/oW4goADl2LIaAa_2sD17XnAWaMurt2SgUBySwNzqkqFYXZBC20QxHTD3EX_SYncR_ceDHDJtvfmDBRD5GRQCKgWpq1IdZT2pNtBr_GDAvUbMfklWjtv1ealsVvfQadgI3u-wnoGryTAkOb2642THKIoNKJ2GhCQOs7LRM6rENHfOEWrsf1t05xl_TR7qtkuXg8CIp54gGQa5X4jGWwLzLxjYM1MkOZmClRxV0PpIwx0440D0WJiY7_2tCsSUZu1dphVPew3lv-zpr6HV8rMRfI0W1Qm7l4o703DiE-LGeG-MxG4GSypiV8vGNzGQQ0IGn7VhL7kK7L487A0IcKvvrqb-q0_jm4tq7ay_XPGWC-rkCV-jfGYtDFZ4JLD4UWj1D4LzExp180jqB0hEu5U5PtHV-Y5_ZmNYDi7WxRKJtAnnCL78u8njMQl5qXkgK5NtGhTTxCjgv_qiMbhEv_TTmnlBG6rM7rAM5lN1AdytPYwORq4nca0eT7Yy25n1SjLYWoFHy7Y5pCda5-Gn3RBS5iD-ik8bQgfuI-m3dVp85xvJAHlMTiDh8JWfjaTPZwS2Q07rHFqS94FHP6aiVT2bwG5SjORdppXR_m4HgeQ=w555-h986-no "Screenshot")

**Comment by frenck** [comment]
Hi there, this add-on has been removed. 

For more information, see the announcement:

<https://community.home-assistant.io/t/community-hass-io-add-on-home-assistant-control-panel/49634/129?u=frenck>

<blockquote><img src="https://community.home-assistant.io/user_avatar/community.home-assistant.io/frenck/200/13184_1.png" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-home-assistant-control-panel/49634/129?u=frenck">Community Hass.io Add-on: Home Assistant Control Panel</a></strong></div><div>Deprecation warning I’m sorry to say, that this add-on is no longer supported or maintained. This add-on required a lot of time to support since a lot of you had issues with getting (and keeping) the control panel in a working state.  This caused an awful lot of support questions, which take a lot of time. This add-on (not the control panel) does not actually do much, which makes it even more painful. Therefore I have decided to drop the add-on.  You can still install this control panel manually...</div></blockquote>
