### ISSUE TITLE
Edit Mode Switch

### ISSUE THREAD

**Issue by marc-gist** [hassio-addons/addon-control-panel#6]
# Problem/Motivation

> edit mode switch is backwards (off allows edit, on function)

## Expected behavior

> Edit mode on, can edit the screen. off can interact with screen

**Comment by frenck** [comment]
Hi there, this add-on has been removed. 

For more information, see the announcement:

<https://community.home-assistant.io/t/community-hass-io-add-on-home-assistant-control-panel/49634/129?u=frenck>

<blockquote><img src="https://community.home-assistant.io/user_avatar/community.home-assistant.io/frenck/200/13184_1.png" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-home-assistant-control-panel/49634/129?u=frenck">Community Hass.io Add-on: Home Assistant Control Panel</a></strong></div><div>Deprecation warning I’m sorry to say, that this add-on is no longer supported or maintained. This add-on required a lot of time to support since a lot of you had issues with getting (and keeping) the control panel in a working state.  This caused an awful lot of support questions, which take a lot of time. This add-on (not the control panel) does not actually do much, which makes it even more painful. Therefore I have decided to drop the add-on.  You can still install this control panel manually...</div></blockquote>
